package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Apuesta generated by hbm2java
 */
public class Apuesta  implements java.io.Serializable {


     private int idApuesta;
     private String nombre;
     private int valorApuesta;

    public Apuesta() {
    }

    public Apuesta(int idApuesta, String nombre, int valorApuesta) {
       this.idApuesta = idApuesta;
       this.nombre = nombre;
       this.valorApuesta = valorApuesta;
    }
   
    public int getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(int idApuesta) {
        this.idApuesta = idApuesta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getValorApuesta() {
        return this.valorApuesta;
    }
    
    public void setValorApuesta(int valorApuesta) {
        this.valorApuesta = valorApuesta;
    }




}


