package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1



/**
 * Apuesta generated by hbm2java
 */
public class Apuesta  implements java.io.Serializable {


     private int idapuesta;
     private int valorMaximo;
     private int valorMinimo;
     private int partidoIdpartido;
     private int boletaIdboleta;

    public Apuesta() {
    }

    public Apuesta(int idapuesta, int valorMaximo, int valorMinimo, int partidoIdpartido, int boletaIdboleta) {
       this.idapuesta = idapuesta;
       this.valorMaximo = valorMaximo;
       this.valorMinimo = valorMinimo;
       this.partidoIdpartido = partidoIdpartido;
       this.boletaIdboleta = boletaIdboleta;
    }
   
    public int getIdapuesta() {
        return this.idapuesta;
    }
    
    public void setIdapuesta(int idapuesta) {
        this.idapuesta = idapuesta;
    }
    public int getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(int valorMaximo) {
        this.valorMaximo = valorMaximo;
    }
    public int getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(int valorMinimo) {
        this.valorMinimo = valorMinimo;
    }
    public int getPartidoIdpartido() {
        return this.partidoIdpartido;
    }
    
    public void setPartidoIdpartido(int partidoIdpartido) {
        this.partidoIdpartido = partidoIdpartido;
    }
    public int getBoletaIdboleta() {
        return this.boletaIdboleta;
    }
    
    public void setBoletaIdboleta(int boletaIdboleta) {
        this.boletaIdboleta = boletaIdboleta;
    }




}


