package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Boleteria generated by hbm2java
 */
public class Boleteria  implements java.io.Serializable {


     private BoleteriaId id;
     private String nombre;

    public Boleteria() {
    }

	
    public Boleteria(BoleteriaId id) {
        this.id = id;
    }
    public Boleteria(BoleteriaId id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public BoleteriaId getId() {
        return this.id;
    }
    
    public void setId(BoleteriaId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


