package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1



/**
 * Boleta generated by hbm2java
 */
public class Boleta  implements java.io.Serializable {


     private int idboleta;
     private int valor;
     private int usuarioIdusuario;

    public Boleta() {
    }

    public Boleta(int idboleta, int valor, int usuarioIdusuario) {
       this.idboleta = idboleta;
       this.valor = valor;
       this.usuarioIdusuario = usuarioIdusuario;
    }
   
    public int getIdboleta() {
        return this.idboleta;
    }
    
    public void setIdboleta(int idboleta) {
        this.idboleta = idboleta;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public int getUsuarioIdusuario() {
        return this.usuarioIdusuario;
    }
    
    public void setUsuarioIdusuario(int usuarioIdusuario) {
        this.usuarioIdusuario = usuarioIdusuario;
    }




}


