package Modelo;
// Generated 23/03/2019 12:44:13 AM by Hibernate Tools 4.3.1



/**
 * Boleta generated by hbm2java
 */
public class Boleta  implements java.io.Serializable {


     private int idboleta;
     private int valor;
     private int usuarioIdusuario;
     private Integer apuestaIdapuesta;
     private int gano;
     private Integer rifaIdrifa;
     private String marcadorApuesta;

    public Boleta() {
    }

	
    public Boleta(int idboleta, int valor, int usuarioIdusuario, int gano) {
        this.idboleta = idboleta;
        this.valor = valor;
        this.usuarioIdusuario = usuarioIdusuario;
        this.gano = gano;
    }
    public Boleta(int idboleta, int valor, int usuarioIdusuario, Integer apuestaIdapuesta, int gano, Integer rifaIdrifa, String marcadorApuesta) {
       this.idboleta = idboleta;
       this.valor = valor;
       this.usuarioIdusuario = usuarioIdusuario;
       this.apuestaIdapuesta = apuestaIdapuesta;
       this.gano = gano;
       this.rifaIdrifa = rifaIdrifa;
       this.marcadorApuesta = marcadorApuesta;
    }
   
    public int getIdboleta() {
        return this.idboleta;
    }
    
    public void setIdboleta(int idboleta) {
        this.idboleta = idboleta;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public int getUsuarioIdusuario() {
        return this.usuarioIdusuario;
    }
    
    public void setUsuarioIdusuario(int usuarioIdusuario) {
        this.usuarioIdusuario = usuarioIdusuario;
    }
    public Integer getApuestaIdapuesta() {
        return this.apuestaIdapuesta;
    }
    
    public void setApuestaIdapuesta(Integer apuestaIdapuesta) {
        this.apuestaIdapuesta = apuestaIdapuesta;
    }
    public int getGano() {
        return this.gano;
    }
    
    public void setGano(int gano) {
        this.gano = gano;
    }
    public Integer getRifaIdrifa() {
        return this.rifaIdrifa;
    }
    
    public void setRifaIdrifa(Integer rifaIdrifa) {
        this.rifaIdrifa = rifaIdrifa;
    }
    public String getMarcadorApuesta() {
        return this.marcadorApuesta;
    }
    
    public void setMarcadorApuesta(String marcadorApuesta) {
        this.marcadorApuesta = marcadorApuesta;
    }




}


