package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * BoleteriaId generated by hbm2java
 */
public class BoleteriaId  implements java.io.Serializable {


     private int idBoleteria;
     private int apuestaIdApuesta;

    public BoleteriaId() {
    }

    public BoleteriaId(int idBoleteria, int apuestaIdApuesta) {
       this.idBoleteria = idBoleteria;
       this.apuestaIdApuesta = apuestaIdApuesta;
    }
   
    public int getIdBoleteria() {
        return this.idBoleteria;
    }
    
    public void setIdBoleteria(int idBoleteria) {
        this.idBoleteria = idBoleteria;
    }
    public int getApuestaIdApuesta() {
        return this.apuestaIdApuesta;
    }
    
    public void setApuestaIdApuesta(int apuestaIdApuesta) {
        this.apuestaIdApuesta = apuestaIdApuesta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BoleteriaId) ) return false;
		 BoleteriaId castOther = ( BoleteriaId ) other; 
         
		 return (this.getIdBoleteria()==castOther.getIdBoleteria())
 && (this.getApuestaIdApuesta()==castOther.getApuestaIdApuesta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBoleteria();
         result = 37 * result + this.getApuestaIdApuesta();
         return result;
   }   


}


