package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Boleta generated by hbm2java
 */
public class Boleta  implements java.io.Serializable {


     private BoletaId id;

    public Boleta() {
    }

    public Boleta(BoletaId id) {
       this.id = id;
    }
   
    public BoletaId getId() {
        return this.id;
    }
    
    public void setId(BoletaId id) {
        this.id = id;
    }




}


