package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * BoletaId generated by hbm2java
 */
public class BoletaId  implements java.io.Serializable {


     private int idBoleta;
     private String nombre;
     private int tipoBoletaIdTipoBoleta;
     private int boleteriaIdBoleteria;
     private int boleteriaApuestaIdApuesta;

    public BoletaId() {
    }

    public BoletaId(int idBoleta, String nombre, int tipoBoletaIdTipoBoleta, int boleteriaIdBoleteria, int boleteriaApuestaIdApuesta) {
       this.idBoleta = idBoleta;
       this.nombre = nombre;
       this.tipoBoletaIdTipoBoleta = tipoBoletaIdTipoBoleta;
       this.boleteriaIdBoleteria = boleteriaIdBoleteria;
       this.boleteriaApuestaIdApuesta = boleteriaApuestaIdApuesta;
    }
   
    public int getIdBoleta() {
        return this.idBoleta;
    }
    
    public void setIdBoleta(int idBoleta) {
        this.idBoleta = idBoleta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getTipoBoletaIdTipoBoleta() {
        return this.tipoBoletaIdTipoBoleta;
    }
    
    public void setTipoBoletaIdTipoBoleta(int tipoBoletaIdTipoBoleta) {
        this.tipoBoletaIdTipoBoleta = tipoBoletaIdTipoBoleta;
    }
    public int getBoleteriaIdBoleteria() {
        return this.boleteriaIdBoleteria;
    }
    
    public void setBoleteriaIdBoleteria(int boleteriaIdBoleteria) {
        this.boleteriaIdBoleteria = boleteriaIdBoleteria;
    }
    public int getBoleteriaApuestaIdApuesta() {
        return this.boleteriaApuestaIdApuesta;
    }
    
    public void setBoleteriaApuestaIdApuesta(int boleteriaApuestaIdApuesta) {
        this.boleteriaApuestaIdApuesta = boleteriaApuestaIdApuesta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BoletaId) ) return false;
		 BoletaId castOther = ( BoletaId ) other; 
         
		 return (this.getIdBoleta()==castOther.getIdBoleta())
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && (this.getTipoBoletaIdTipoBoleta()==castOther.getTipoBoletaIdTipoBoleta())
 && (this.getBoleteriaIdBoleteria()==castOther.getBoleteriaIdBoleteria())
 && (this.getBoleteriaApuestaIdApuesta()==castOther.getBoleteriaApuestaIdApuesta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBoleta();
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + this.getTipoBoletaIdTipoBoleta();
         result = 37 * result + this.getBoleteriaIdBoleteria();
         result = 37 * result + this.getBoleteriaApuestaIdApuesta();
         return result;
   }   


}


