package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * CatalogoRifa generated by hbm2java
 */
public class CatalogoRifa  implements java.io.Serializable {


     private int idCatalogoRifa;
     private String nombreEvento;

    public CatalogoRifa() {
    }

	
    public CatalogoRifa(int idCatalogoRifa) {
        this.idCatalogoRifa = idCatalogoRifa;
    }
    public CatalogoRifa(int idCatalogoRifa, String nombreEvento) {
       this.idCatalogoRifa = idCatalogoRifa;
       this.nombreEvento = nombreEvento;
    }
   
    public int getIdCatalogoRifa() {
        return this.idCatalogoRifa;
    }
    
    public void setIdCatalogoRifa(int idCatalogoRifa) {
        this.idCatalogoRifa = idCatalogoRifa;
    }
    public String getNombreEvento() {
        return this.nombreEvento;
    }
    
    public void setNombreEvento(String nombreEvento) {
        this.nombreEvento = nombreEvento;
    }




}


