package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * DeporteId generated by hbm2java
 */
public class DeporteId  implements java.io.Serializable {


     private int idDeporte;
     private int torneoIdTorneo;

    public DeporteId() {
    }

    public DeporteId(int idDeporte, int torneoIdTorneo) {
       this.idDeporte = idDeporte;
       this.torneoIdTorneo = torneoIdTorneo;
    }
   
    public int getIdDeporte() {
        return this.idDeporte;
    }
    
    public void setIdDeporte(int idDeporte) {
        this.idDeporte = idDeporte;
    }
    public int getTorneoIdTorneo() {
        return this.torneoIdTorneo;
    }
    
    public void setTorneoIdTorneo(int torneoIdTorneo) {
        this.torneoIdTorneo = torneoIdTorneo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeporteId) ) return false;
		 DeporteId castOther = ( DeporteId ) other; 
         
		 return (this.getIdDeporte()==castOther.getIdDeporte())
 && (this.getTorneoIdTorneo()==castOther.getTorneoIdTorneo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDeporte();
         result = 37 * result + this.getTorneoIdTorneo();
         return result;
   }   


}


