package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1



/**
 * Deporte generated by hbm2java
 */
public class Deporte  implements java.io.Serializable {


     private int iddeporte;
     private String nombre;
     private int torneoIdtorneo;

    public Deporte() {
    }

    public Deporte(int iddeporte, String nombre, int torneoIdtorneo) {
       this.iddeporte = iddeporte;
       this.nombre = nombre;
       this.torneoIdtorneo = torneoIdtorneo;
    }
   
    public int getIddeporte() {
        return this.iddeporte;
    }
    
    public void setIddeporte(int iddeporte) {
        this.iddeporte = iddeporte;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getTorneoIdtorneo() {
        return this.torneoIdtorneo;
    }
    
    public void setTorneoIdtorneo(int torneoIdtorneo) {
        this.torneoIdtorneo = torneoIdtorneo;
    }




}


