package Modelo;
// Generated 23/03/2019 12:44:13 AM by Hibernate Tools 4.3.1



/**
 * Deporte generated by hbm2java
 */
public class Deporte  implements java.io.Serializable {


     private int iddeporte;
     private String nombre;

    public Deporte() {
    }

    public Deporte(int iddeporte, String nombre) {
       this.iddeporte = iddeporte;
       this.nombre = nombre;
    }
   
    public int getIddeporte() {
        return this.iddeporte;
    }
    
    public void setIddeporte(int iddeporte) {
        this.iddeporte = iddeporte;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


