package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Deporte generated by hbm2java
 */
public class Deporte  implements java.io.Serializable {


     private DeporteId id;
     private String nombre;

    public Deporte() {
    }

	
    public Deporte(DeporteId id) {
        this.id = id;
    }
    public Deporte(DeporteId id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public DeporteId getId() {
        return this.id;
    }
    
    public void setId(DeporteId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


