package Modelo;
// Generated 23/03/2019 12:44:13 AM by Hibernate Tools 4.3.1



/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private int idequipo;
     private String nombreEquipo;
     private int deporteIddeporte;

    public Equipo() {
    }

    public Equipo(int idequipo, String nombreEquipo, int deporteIddeporte) {
       this.idequipo = idequipo;
       this.nombreEquipo = nombreEquipo;
       this.deporteIddeporte = deporteIddeporte;
    }
   
    public int getIdequipo() {
        return this.idequipo;
    }
    
    public void setIdequipo(int idequipo) {
        this.idequipo = idequipo;
    }
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }
    public int getDeporteIddeporte() {
        return this.deporteIddeporte;
    }
    
    public void setDeporteIddeporte(int deporteIddeporte) {
        this.deporteIddeporte = deporteIddeporte;
    }




}


