package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private EquipoId id;
     private String nombre;

    public Equipo() {
    }

	
    public Equipo(EquipoId id) {
        this.id = id;
    }
    public Equipo(EquipoId id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public EquipoId getId() {
        return this.id;
    }
    
    public void setId(EquipoId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


