package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * EquipoId generated by hbm2java
 */
public class EquipoId  implements java.io.Serializable {


     private int idEquipo;
     private int deporteIdDeporte;

    public EquipoId() {
    }

    public EquipoId(int idEquipo, int deporteIdDeporte) {
       this.idEquipo = idEquipo;
       this.deporteIdDeporte = deporteIdDeporte;
    }
   
    public int getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    public int getDeporteIdDeporte() {
        return this.deporteIdDeporte;
    }
    
    public void setDeporteIdDeporte(int deporteIdDeporte) {
        this.deporteIdDeporte = deporteIdDeporte;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EquipoId) ) return false;
		 EquipoId castOther = ( EquipoId ) other; 
         
		 return (this.getIdEquipo()==castOther.getIdEquipo())
 && (this.getDeporteIdDeporte()==castOther.getDeporteIdDeporte());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEquipo();
         result = 37 * result + this.getDeporteIdDeporte();
         return result;
   }   


}


