package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1



/**
 * Ganador generated by hbm2java
 */
public class Ganador  implements java.io.Serializable {


     private int idganador;
     private int boletaIdboleta;

    public Ganador() {
    }

    public Ganador(int idganador, int boletaIdboleta) {
       this.idganador = idganador;
       this.boletaIdboleta = boletaIdboleta;
    }
   
    public int getIdganador() {
        return this.idganador;
    }
    
    public void setIdganador(int idganador) {
        this.idganador = idganador;
    }
    public int getBoletaIdboleta() {
        return this.boletaIdboleta;
    }
    
    public void setBoletaIdboleta(int boletaIdboleta) {
        this.boletaIdboleta = boletaIdboleta;
    }




}


