package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private int idJugador;
     private String nombre;
     private Integer edad;
     private int equipoIdEquipo;

    public Jugador() {
    }

	
    public Jugador(int idJugador, String nombre, int equipoIdEquipo) {
        this.idJugador = idJugador;
        this.nombre = nombre;
        this.equipoIdEquipo = equipoIdEquipo;
    }
    public Jugador(int idJugador, String nombre, Integer edad, int equipoIdEquipo) {
       this.idJugador = idJugador;
       this.nombre = nombre;
       this.edad = edad;
       this.equipoIdEquipo = equipoIdEquipo;
    }
   
    public int getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(int idJugador) {
        this.idJugador = idJugador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public int getEquipoIdEquipo() {
        return this.equipoIdEquipo;
    }
    
    public void setEquipoIdEquipo(int equipoIdEquipo) {
        this.equipoIdEquipo = equipoIdEquipo;
    }




}


