package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private MarcadorId id;
     private Integer marcadorLocal;
     private Integer marcadorVisitante;

    public Marcador() {
    }

	
    public Marcador(MarcadorId id) {
        this.id = id;
    }
    public Marcador(MarcadorId id, Integer marcadorLocal, Integer marcadorVisitante) {
       this.id = id;
       this.marcadorLocal = marcadorLocal;
       this.marcadorVisitante = marcadorVisitante;
    }
   
    public MarcadorId getId() {
        return this.id;
    }
    
    public void setId(MarcadorId id) {
        this.id = id;
    }
    public Integer getMarcadorLocal() {
        return this.marcadorLocal;
    }
    
    public void setMarcadorLocal(Integer marcadorLocal) {
        this.marcadorLocal = marcadorLocal;
    }
    public Integer getMarcadorVisitante() {
        return this.marcadorVisitante;
    }
    
    public void setMarcadorVisitante(Integer marcadorVisitante) {
        this.marcadorVisitante = marcadorVisitante;
    }




}


