package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * MarcadorId generated by hbm2java
 */
public class MarcadorId  implements java.io.Serializable {


     private int idMarcador;
     private int apuestaIdApuesta;

    public MarcadorId() {
    }

    public MarcadorId(int idMarcador, int apuestaIdApuesta) {
       this.idMarcador = idMarcador;
       this.apuestaIdApuesta = apuestaIdApuesta;
    }
   
    public int getIdMarcador() {
        return this.idMarcador;
    }
    
    public void setIdMarcador(int idMarcador) {
        this.idMarcador = idMarcador;
    }
    public int getApuestaIdApuesta() {
        return this.apuestaIdApuesta;
    }
    
    public void setApuestaIdApuesta(int apuestaIdApuesta) {
        this.apuestaIdApuesta = apuestaIdApuesta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MarcadorId) ) return false;
		 MarcadorId castOther = ( MarcadorId ) other; 
         
		 return (this.getIdMarcador()==castOther.getIdMarcador())
 && (this.getApuestaIdApuesta()==castOther.getApuestaIdApuesta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMarcador();
         result = 37 * result + this.getApuestaIdApuesta();
         return result;
   }   


}


