package Modelo;
// Generated 22/03/2019 12:45:38 AM by Hibernate Tools 4.3.1



/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private int idpartido;
     private int equipoLocal;
     private int equipoVisitante;
     private String fecha;
     private String marcador;
     private String fechaInicio;
     private String fechaFin;

    public Partido() {
    }

    public Partido(int idpartido, int equipoLocal, int equipoVisitante, String fecha, String marcador, String fechaInicio, String fechaFin) {
       this.idpartido = idpartido;
       this.equipoLocal = equipoLocal;
       this.equipoVisitante = equipoVisitante;
       this.fecha = fecha;
       this.marcador = marcador;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getIdpartido() {
        return this.idpartido;
    }
    
    public void setIdpartido(int idpartido) {
        this.idpartido = idpartido;
    }
    public int getEquipoLocal() {
        return this.equipoLocal;
    }
    
    public void setEquipoLocal(int equipoLocal) {
        this.equipoLocal = equipoLocal;
    }
    public int getEquipoVisitante() {
        return this.equipoVisitante;
    }
    
    public void setEquipoVisitante(int equipoVisitante) {
        this.equipoVisitante = equipoVisitante;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(String marcador) {
        this.marcador = marcador;
    }
    public String getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }




}


