package Modelo;
// Generated 23/03/2019 12:44:13 AM by Hibernate Tools 4.3.1



/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private int idpartido;
     private int equipoLocal;
     private int equipoVisitante;
     private String fecha;
     private String marcador;
     private String horaInicio;
     private String horaFin;

    public Partido() {
    }

    public Partido(int idpartido, int equipoLocal, int equipoVisitante, String fecha, String marcador, String horaInicio, String horaFin) {
       this.idpartido = idpartido;
       this.equipoLocal = equipoLocal;
       this.equipoVisitante = equipoVisitante;
       this.fecha = fecha;
       this.marcador = marcador;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
    public int getIdpartido() {
        return this.idpartido;
    }
    
    public void setIdpartido(int idpartido) {
        this.idpartido = idpartido;
    }
    public int getEquipoLocal() {
        return this.equipoLocal;
    }
    
    public void setEquipoLocal(int equipoLocal) {
        this.equipoLocal = equipoLocal;
    }
    public int getEquipoVisitante() {
        return this.equipoVisitante;
    }
    
    public void setEquipoVisitante(int equipoVisitante) {
        this.equipoVisitante = equipoVisitante;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(String marcador) {
        this.marcador = marcador;
    }
    public String getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }
    public String getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(String horaFin) {
        this.horaFin = horaFin;
    }




}


