package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private int idpartido;
     private int equipoLocal;
     private int equipoVisitante;
     private Date fecha;
     private String marcador;
     private int torneoIdtorneo;

    public Partido() {
    }

    public Partido(int idpartido, int equipoLocal, int equipoVisitante, Date fecha, String marcador, int torneoIdtorneo) {
       this.idpartido = idpartido;
       this.equipoLocal = equipoLocal;
       this.equipoVisitante = equipoVisitante;
       this.fecha = fecha;
       this.marcador = marcador;
       this.torneoIdtorneo = torneoIdtorneo;
    }
   
    public int getIdpartido() {
        return this.idpartido;
    }
    
    public void setIdpartido(int idpartido) {
        this.idpartido = idpartido;
    }
    public int getEquipoLocal() {
        return this.equipoLocal;
    }
    
    public void setEquipoLocal(int equipoLocal) {
        this.equipoLocal = equipoLocal;
    }
    public int getEquipoVisitante() {
        return this.equipoVisitante;
    }
    
    public void setEquipoVisitante(int equipoVisitante) {
        this.equipoVisitante = equipoVisitante;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(String marcador) {
        this.marcador = marcador;
    }
    public int getTorneoIdtorneo() {
        return this.torneoIdtorneo;
    }
    
    public void setTorneoIdtorneo(int torneoIdtorneo) {
        this.torneoIdtorneo = torneoIdtorneo;
    }




}


