package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * ParticipanteId generated by hbm2java
 */
public class ParticipanteId  implements java.io.Serializable {


     private int idParticipante;
     private int apuestaIdApuesta;

    public ParticipanteId() {
    }

    public ParticipanteId(int idParticipante, int apuestaIdApuesta) {
       this.idParticipante = idParticipante;
       this.apuestaIdApuesta = apuestaIdApuesta;
    }
   
    public int getIdParticipante() {
        return this.idParticipante;
    }
    
    public void setIdParticipante(int idParticipante) {
        this.idParticipante = idParticipante;
    }
    public int getApuestaIdApuesta() {
        return this.apuestaIdApuesta;
    }
    
    public void setApuestaIdApuesta(int apuestaIdApuesta) {
        this.apuestaIdApuesta = apuestaIdApuesta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipanteId) ) return false;
		 ParticipanteId castOther = ( ParticipanteId ) other; 
         
		 return (this.getIdParticipante()==castOther.getIdParticipante())
 && (this.getApuestaIdApuesta()==castOther.getApuestaIdApuesta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdParticipante();
         result = 37 * result + this.getApuestaIdApuesta();
         return result;
   }   


}


