package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Participante generated by hbm2java
 */
public class Participante  implements java.io.Serializable {


     private ParticipanteId id;
     private String nombre;
     private String celular;

    public Participante() {
    }

	
    public Participante(ParticipanteId id) {
        this.id = id;
    }
    public Participante(ParticipanteId id, String nombre, String celular) {
       this.id = id;
       this.nombre = nombre;
       this.celular = celular;
    }
   
    public ParticipanteId getId() {
        return this.id;
    }
    
    public void setId(ParticipanteId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }




}


