package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Premio generated by hbm2java
 */
public class Premio  implements java.io.Serializable {


     private int idPremio;
     private String nombre;
     private Integer valorPremio;

    public Premio() {
    }

	
    public Premio(int idPremio) {
        this.idPremio = idPremio;
    }
    public Premio(int idPremio, String nombre, Integer valorPremio) {
       this.idPremio = idPremio;
       this.nombre = nombre;
       this.valorPremio = valorPremio;
    }
   
    public int getIdPremio() {
        return this.idPremio;
    }
    
    public void setIdPremio(int idPremio) {
        this.idPremio = idPremio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getValorPremio() {
        return this.valorPremio;
    }
    
    public void setValorPremio(Integer valorPremio) {
        this.valorPremio = valorPremio;
    }




}


