package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * RifaHasCatalogoRifa generated by hbm2java
 */
public class RifaHasCatalogoRifa  implements java.io.Serializable {


     private RifaHasCatalogoRifaId id;

    public RifaHasCatalogoRifa() {
    }

    public RifaHasCatalogoRifa(RifaHasCatalogoRifaId id) {
       this.id = id;
    }
   
    public RifaHasCatalogoRifaId getId() {
        return this.id;
    }
    
    public void setId(RifaHasCatalogoRifaId id) {
        this.id = id;
    }




}


