package Modelo;
// Generated 22/03/2019 12:45:38 AM by Hibernate Tools 4.3.1



/**
 * Rifa generated by hbm2java
 */
public class Rifa  implements java.io.Serializable {


     private int idrifa;
     private String premio;
     private int numeroBoletas;
     private String fechaInicio;
     private String fechaFin;

    public Rifa() {
    }

    public Rifa(int idrifa, String premio, int numeroBoletas, String fechaInicio, String fechaFin) {
       this.idrifa = idrifa;
       this.premio = premio;
       this.numeroBoletas = numeroBoletas;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getIdrifa() {
        return this.idrifa;
    }
    
    public void setIdrifa(int idrifa) {
        this.idrifa = idrifa;
    }
    public String getPremio() {
        return this.premio;
    }
    
    public void setPremio(String premio) {
        this.premio = premio;
    }
    public int getNumeroBoletas() {
        return this.numeroBoletas;
    }
    
    public void setNumeroBoletas(int numeroBoletas) {
        this.numeroBoletas = numeroBoletas;
    }
    public String getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }




}


