package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Rifa generated by hbm2java
 */
public class Rifa  implements java.io.Serializable {


     private RifaId id;
     private String nombre;

    public Rifa() {
    }

	
    public Rifa(RifaId id) {
        this.id = id;
    }
    public Rifa(RifaId id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public RifaId getId() {
        return this.id;
    }
    
    public void setId(RifaId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


