package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rifa generated by hbm2java
 */
public class Rifa  implements java.io.Serializable {


     private int idrifa;
     private String nombre;
     private String premio;
     private int numeroBoletas;
     private Date fechaInicio;
     private Date fechaFin;
     private int boletaIdboleta;

    public Rifa() {
    }

    public Rifa(int idrifa, String nombre, String premio, int numeroBoletas, Date fechaInicio, Date fechaFin, int boletaIdboleta) {
       this.idrifa = idrifa;
       this.nombre = nombre;
       this.premio = premio;
       this.numeroBoletas = numeroBoletas;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.boletaIdboleta = boletaIdboleta;
    }
   
    public int getIdrifa() {
        return this.idrifa;
    }
    
    public void setIdrifa(int idrifa) {
        this.idrifa = idrifa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPremio() {
        return this.premio;
    }
    
    public void setPremio(String premio) {
        this.premio = premio;
    }
    public int getNumeroBoletas() {
        return this.numeroBoletas;
    }
    
    public void setNumeroBoletas(int numeroBoletas) {
        this.numeroBoletas = numeroBoletas;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public int getBoletaIdboleta() {
        return this.boletaIdboleta;
    }
    
    public void setBoletaIdboleta(int boletaIdboleta) {
        this.boletaIdboleta = boletaIdboleta;
    }




}


