package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Torneo generated by hbm2java
 */
public class Torneo  implements java.io.Serializable {


     private int idtorneo;
     private String nombre;
     private Date fechaInicio;
     private Date fechaFin;

    public Torneo() {
    }

    public Torneo(int idtorneo, String nombre, Date fechaInicio, Date fechaFin) {
       this.idtorneo = idtorneo;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getIdtorneo() {
        return this.idtorneo;
    }
    
    public void setIdtorneo(int idtorneo) {
        this.idtorneo = idtorneo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


