package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * Torneo generated by hbm2java
 */
public class Torneo  implements java.io.Serializable {


     private int idTorneo;
     private String nombre;

    public Torneo() {
    }

	
    public Torneo(int idTorneo) {
        this.idTorneo = idTorneo;
    }
    public Torneo(int idTorneo, String nombre) {
       this.idTorneo = idTorneo;
       this.nombre = nombre;
    }
   
    public int getIdTorneo() {
        return this.idTorneo;
    }
    
    public void setIdTorneo(int idTorneo) {
        this.idTorneo = idTorneo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


