package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1



/**
 * UsuarioHasEquipo generated by hbm2java
 */
public class UsuarioHasEquipo  implements java.io.Serializable {


     private UsuarioHasEquipoId id;

    public UsuarioHasEquipo() {
    }

    public UsuarioHasEquipo(UsuarioHasEquipoId id) {
       this.id = id;
    }
   
    public UsuarioHasEquipoId getId() {
        return this.id;
    }
    
    public void setId(UsuarioHasEquipoId id) {
        this.id = id;
    }




}


