package Modelo;
// Generated 22/03/2019 12:45:38 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombres;
     private String apellidos;
     private int identificacion;
     private int rolIdrol;

    public Usuario() {
    }

    public Usuario(int idusuario, String nombres, String apellidos, int identificacion, int rolIdrol) {
       this.idusuario = idusuario;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.identificacion = identificacion;
       this.rolIdrol = rolIdrol;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }
    public int getRolIdrol() {
        return this.rolIdrol;
    }
    
    public void setRolIdrol(int rolIdrol) {
        this.rolIdrol = rolIdrol;
    }




}


