package Modelo;
// Generated 20/03/2019 05:41:14 PM by Hibernate Tools 4.3.1



/**
 * UsuarioHasEquipoId generated by hbm2java
 */
public class UsuarioHasEquipoId  implements java.io.Serializable {


     private int usuarioIdusuario;
     private int equipoIdequipo;

    public UsuarioHasEquipoId() {
    }

    public UsuarioHasEquipoId(int usuarioIdusuario, int equipoIdequipo) {
       this.usuarioIdusuario = usuarioIdusuario;
       this.equipoIdequipo = equipoIdequipo;
    }
   
    public int getUsuarioIdusuario() {
        return this.usuarioIdusuario;
    }
    
    public void setUsuarioIdusuario(int usuarioIdusuario) {
        this.usuarioIdusuario = usuarioIdusuario;
    }
    public int getEquipoIdequipo() {
        return this.equipoIdequipo;
    }
    
    public void setEquipoIdequipo(int equipoIdequipo) {
        this.equipoIdequipo = equipoIdequipo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioHasEquipoId) ) return false;
		 UsuarioHasEquipoId castOther = ( UsuarioHasEquipoId ) other; 
         
		 return (this.getUsuarioIdusuario()==castOther.getUsuarioIdusuario())
 && (this.getEquipoIdequipo()==castOther.getEquipoIdequipo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioIdusuario();
         result = 37 * result + this.getEquipoIdequipo();
         return result;
   }   


}


