package Modelo;
// Generated 13/03/2019 12:05:59 AM by Hibernate Tools 4.3.1



/**
 * VentaBoletas generated by hbm2java
 */
public class VentaBoletas  implements java.io.Serializable {


     private VentaBoletasId id;
     private String ventaBoletascol;

    public VentaBoletas() {
    }

	
    public VentaBoletas(VentaBoletasId id) {
        this.id = id;
    }
    public VentaBoletas(VentaBoletasId id, String ventaBoletascol) {
       this.id = id;
       this.ventaBoletascol = ventaBoletascol;
    }
   
    public VentaBoletasId getId() {
        return this.id;
    }
    
    public void setId(VentaBoletasId id) {
        this.id = id;
    }
    public String getVentaBoletascol() {
        return this.ventaBoletascol;
    }
    
    public void setVentaBoletascol(String ventaBoletascol) {
        this.ventaBoletascol = ventaBoletascol;
    }




}


